[package]
authors = ["Joseph Lai"]
edition = "2021"
name = "frontend"
version = "1.0.0"

[dependencies]
gloo-net = { version = "0.2.6", features = ["http"] }
wasm-cookies = "0.1.0"
yew = { version = "0.20.0", features = ["csr"] }
yew-router = "0.17.0"
